### ISSUE TITLE
Frontend: URL Social Media

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#101]
Please add the Social Media URLs to the side navigation:

Youtube: https://www.youtube.com/channel/UCe5cvHdDNOyVfUyy0X8-M8Q
Facebook: https://www.facebook.com/TrufiAssoc
Twitter: https://twitter.com/TrufiAssoc
LinkdIn: https://www.linkedin.com/company/trufi-association/

**Comment by AnivlisLuz** [comment]
The Youtube URL is wrong.
