### ISSUE TITLE
Map background

### ISSUE THREAD

**Issue by ValorNaram** [trufi-association/hamburg-bike-app#110]
Using our own tileserver:

**Trufi Liberty** `https://api.trufi.app/tileserver-hamburg/styles/trufi-liberty/{z}/{x}/{y}{r}.png` based on the template `osm liberty` (only changed colour of major highway)
**Trufi Dark** ` https://api.trufi.app/tileserver-hamburg/styles/trufi-dark/{z}/{x}/{y}{r}.png` based on the template `dark matter` (highly customized by me)

**Comment by ValorNaram** [comment]
Necessary map tile attribution: `C Tileserver C OpenStreetMap Contributors` . Please replace the big `C` with the copyright symbol.

**Comment by SamuelRioTz** [comment]
![Screen Shot 2021-09-29 at 19 42 40](https://user-images.githubusercontent.com/43000324/135363219-581d9ab4-30c7-4615-8a37-3383feceb34e.png)
@ValorNaram I guess the tile server is down
https://api.trufi.app/tileserver-bikeapphamburg/styles/trufi-liberty/13/4322/2645@2x.png

**Comment by ValorNaram** [comment]
Please try again with https://api.trufi.app/tileserver-hamburg/styles/trufi-liberty/13/4322/2645@2x.png

**Comment by ValorNaram** [comment]
**Note:** I changed the url a bit. See my updated issue text at https://github.com/trufi-association/hamburg-bike-app/issues/110#issue-1011241298

**Comment by SamuelRioTz** [comment]
@ZihRah @AnivlisLuz @ValorNaram that is how the new map types looks
![Screen Shot 2021-09-30 at 14 40 25](https://user-images.githubusercontent.com/43000324/135512350-faa6d1bb-3cd9-4b9b-a38f-b4b1958d62f7.png)
![Screen Shot 2021-09-30 at 14 40 44](https://user-images.githubusercontent.com/43000324/135512387-dfffbd8f-c128-485f-a96f-6b427ebe2839.png)

**Comment by ZihRah** [comment]
The problem we have here now is that the grey route of the bicycle isn't really visible anymore on the dark map. Can we make it light grey or white?

**Comment by SamuelRioTz** [comment]
@ZihRah  change the route depending on the map is too complex, so I suggest to stay with the agreement of avoid the dark map for this MVP

**Comment by ValorNaram** [comment]
I can try to modify the map so the grey is visible but the app is not working for me.On 2 Oct 2021 3:33 pm, Samuel Rioja ***@***.***> wrote:
@ZihRah  change the route depending on the map is too complex, so I suggest to stay with the agreement of avoid the dark map for this MVP

**Comment by SamuelRioTz** [comment]
@ValorNaram  I just upload a hot fix, please update the app to the last **version 23 (1.4.2)**

**Comment by ZihRah** [comment]
@SamuelRioTz @ValorNaram It is fine with me when we stick to the plan to hide the dark map. Please let me know once you hide it, so I can do the review :)
