### ISSUE TITLE
Frontend: One minor change in the About Text EN/DE

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#117]
Please change in the about view in the german version the following:

Deshalb haben wir von Trufi Association im Auftrag der ITS und der hvv GmbH Nägel mit Köpfen gemacht und voilà: Hier ist Nicht ohne mein Rad Hamburg!

It is at the end of the first long paragraph. And keep it bold but leave out the quotation marks.

It is the same in the English version: ..., and violà, here it is: Nicht ohne mein Rad Hamburg!
Here is a full-stopp which has to be deleted  before the exclamation mark.

**Comment by GustavoTCh** [comment]
@ZihRah In German-version is "Hier ist Nicht ohne mein Rad Hamburg!" or "Hier ist sie die Nicht ohne mein Rad Hamburg!"?
