### ISSUE TITLE
Frontend: Splachscreen Change of writting

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#123]
Please write Powered by Trufi Association e. V.

![Screenshot_20211002-195907](https://user-images.githubusercontent.com/70654680/135733009-6965ddf3-9d99-4af5-8276-fb2168064dce.jpg)

Please ignore the question mark at the button as this was clarified already :)

**Comment by SamuelRioTz** [comment]
is not possible to use localization on splash screen

**Comment by ZihRah** [comment]
Only cange Trufi to Trufi Association e. V.
