### ISSUE TITLE
Provision of Server instance & GTFS

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#14]

**Comment by ValorNaram** [comment]
- [x] Finding Tileserver
- [ ] Fetching GTFS and Street Data of Hamburg (probably done, just needs to be updated)
- [ ] Fetching POI's (Stops, known places, etc.) for easy searching (probably done, just needs to be updated)
- [ ] Preparing OTP 2
- [ ] Preparing Nginx and HTTPS Certificate

## Tile Server Details
We will use an external Tile Service for "Hamburg Bike App" for now until we have something on our own or agreed on a Trufi wide standard. Here are details:
Url: `https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png`
Substitute `{s}` with a ,b ,c or d .
Attribution: `&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>`

**Comment by ValorNaram** [comment]
Created `otp-config.json` under `graph` containing the following:

```json
{
  "otpFeatures" : {
    "SandboxAPILegacyGraphQLApi": true
  }
}

so development team can use their existing implementation of the GraphQL query format.

```

**Comment by ValorNaram** [comment]
Awaiting approval/ok by @SamuelRioTz and/or @GustavoTCh .

**Comment by ValorNaram** [comment]
- [ ] Fix "GraphQL API Url missing"
