### ISSUE TITLE
Incorporation of UI/UX Design

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#31]
- [x]  View 1 a: nothing to do here jet
- [x] View 1b: Please add start/end field, reverse arrows, time/date picker, add a slider for choosing if it's more bike or publik transport and add a button with rounded edges
- [x] View 1c: Add only three results and add a Button show more - maybe with a ghost button and rounded edges.
- [ ] View 2a Variant 3: The part of the display that shows the details should be minimizable and maximizable. The concrete colours for indicating important points of the route will follow. The position point on the map should move later and display the current position of the User.

**Comment by GustavoTCh** [comment]
Resolved points in this PR https://github.com/trufi-association/trufi-core/pull/571
