### ISSUE TITLE
Creation of Imprint View

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#47]
Text for the view:

Impressum
Angaben gemäß § 5 TMG:
Trufi Association e.V.
Postanschrift:
Rodenbeker Str. 18c
22935 Hamburg
Kontakt:
Telefon: +491634791397
E-Mail: info@trufi-association.org
Vertreten durch:
Christoph Hanser (Vorsitzender)
Eingetragen am
Amtsgericht Hamburg
VR 24026
Hinweise zur Website
Information gemäß § 36 VSBG
Gemäß § 36 VSBG (Verbraucherstreitbeilegungsgesetz – Gesetz über die alternative Streitbeilegung in Verbrauchersachen) erklärt der Betreiber dieser Website:
Wir sind weder bereit noch verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.

**Comment by swrengel** [comment]
like this ? 

https://xd.adobe.com/view/aa1c8358-7995-406d-bca2-3b25b32cf0e6-ff4f/
