### ISSUE TITLE
Setting up off-times for bikes in the frontend

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#50]
As we can't solve the problem to calculate in off-times for bikes in the backend the idea is that you set something up to make the system switch during the off-hours and show only bike routes. You'll find the off times here: https://www.hvv.de/de/fahrrad

**Comment by ZihRah** [comment]
At these times you are allowed to take your bike to the public vehicles:
mo.-fr. until 6 am
from 9am to 4pm 
from 6pm until end of operation
Saturdays and Sundays and on holidays bikes are allowed the entire day.

NOT ALLOWED
not allowed from 6am to 9am
not allowed from 4pm to 6 pm

06:00-09:00
16:00-18:00

In the above-mentioned time frames please show just bike.

**Comment by JoeRossberg** [comment]
If I select a time e.g. 17:18 wich is 5:18 pm and in the blocking time we still show results with public transportation legs in rail/train/tube. So the bug is still there ( persistent ).

**Comment by SamuelRioTz** [comment]
@JoeRossberg you are right, the issue is tested and fixed, could test it again in the new version(1.3.9+20)?

**Comment by JoeRossberg** [comment]
Hi Samuel,

sure I will test it today with version 20.

I will add my comment to #50 + #84.

Brgds.
Joe

**Comment by ZihRah** [comment]
The off-times only work, when we are actually in the time frame of off-times. But when we look up a point of time in future it doesn't work. @ValorNaram Can you try and fix it until tomorrow 3rd of October? Otherwise it unfortunately has to stay as it is.
![Bild von iOS](https://user-images.githubusercontent.com/70654680/135732687-c644ec7f-66bb-425e-95a2-9b8e4ea150b9.png)
![Bild von iOS (1)](https://user-images.githubusercontent.com/70654680/135732690-56458854-ac3b-4941-a67d-83d333022736.png)

**Comment by SamuelRioTz** [comment]
@ZihRah fixed, the problem was with conditions
