### ISSUE TITLE
Backend/ Frontend: Drop-down how much bike do you want to ride

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#55]
Preparing the technical aspect for this request.

# Backend
![image](https://user-images.githubusercontent.com/19347636/133134309-ccdaa705-1eca-4668-b823-3faa90fc43cb.png)

## Understanding

| GUI | Parameter (machine readable) |
| :----: | :--------------: |
| Quick | triangleTimeFactor  |
| Flat    | triangleSlopeFactor |
| Bike Friendly | triangleSafetyFactor |

% converts to decimal ( 100% = 1, 0% - 0.50% = 0.50 )

E.g. triangleSlopeFactor=1 means 100% on "Flat" which yells for me only cycling routes. triangleSlopeFactor=0 means 0% on "Flat".

## Indicator how much bike you want to ride

The dropdown sets the following query parameters:
- "Mehr ÖPNV" --> set `mode=TRANSIT,BICYCLE`, `triangleTimeFactor=0.5555555555555556`, `triangleSlopeFactor=0.1555636246842562` and `triangleSafetyFactor=0.2888808197601882`
- "Beides" --> set `mode=TRANSIT,BICYCLE`
- "Mehr Rad" --> set `mode=TRANSIT,BICYCLE`, `triangleTimeFactor=0.32098765432098764`, `triangleSlopeFactor=0.1873142020882622` and `triangleSafetyFactor=0.5555555555555556`.

# Frontend

The dropdown "how much bike do you want to ride" contains the following choosable items:
- "Mehr Rad"
- "Beides"
- "Mehr ÖPNV"

**Comment by ValorNaram** [comment]
@SamuelRioTz Can you work with that? Others like @swrengel should add ux/ui friendly labels to it.

**Comment by ValorNaram** [comment]
@swrengel I updated the labels as you wrote them in Slack. @SamuelRioTz I finished finetuning the parameters you need to send to the backend. They are now final from my site so you can now work with them without having to worry that I change something.

**Comment by SamuelRioTz** [comment]
@GustavoTCh

**Comment by GustavoTCh** [comment]
@SamuelRioTz  yes, we can work with this.
