### ISSUE TITLE
Frontend: Implementation Search 1.1

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#59]
Implementation of the changes in Search 1.1 & 1.2:
https://xd.adobe.com/view/4125824f-31a3-4d8c-983d-63ed93f8b80b-1476/screen/ac759c40-aaf3-4495-82e9-6676c25378f6/ 

https://xd.adobe.com/view/4125824f-31a3-4d8c-983d-63ed93f8b80b-1476/screen/41739390-a038-4f13-abab-a8ec97c43772/

Take care of the Name: It is 'Nicht ohne mein Rad' now.

**Comment by GustavoTCh** [comment]
Hi @ZihRah, 'Nicht ohne mein Rad' replaces 'Bike & Banh' or 'Moin'?
![Screen Shot 2021-09-19 at 11 13 06](https://user-images.githubusercontent.com/42806689/133932850-a6b6f34c-7fee-430a-a6bc-bf2cdf406f1b.png)

**Comment by ValorNaram** [comment]
It replaces "Bike & Bahn". "Moin" is a north german expression for saying "Hey".
