### ISSUE TITLE
UI/UX Design Creation of Splash Screen

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#6]

**Comment by swrengel** [comment]
3 ideas for the Screen: 


![
![Uploading Splashscreen-2.jpg…
![Splashscreen-3](https://user-images.githubusercontent.com/72873881/132957651-199c980a-16bc-4f71-9e7f-3cc667f61f16.jpg)
]()
Uploading Splashscreen-1.jpg…]()

**Comment by swrengel** [comment]
1,2 or 3?   What do you think? 

https://xd.adobe.com/view/c2c2de14-dc79-49fd-b8ba-674ee841176b-9791/
