### ISSUE TITLE
Design/Frontend: Colour code of vehicles

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#72]
Sandra sends Samuel the right colour codes of the public transport vehicles in Hamburg.

**Comment by ValorNaram** [comment]
@SamuelRioTz I can save the colour codes in a JSON configuration which the app can then fetch. Displaying the routes is not the task of a backend.

**Comment by SamuelRioTz** [comment]
@ValorNaram the colors should be part of the route properties.
I mean inside the gtfs file https://developers.google.com/transit/gtfs/reference#routestxt
that is what we are using for show the colors. 
@GustavoTCh could you confirm that pls
![Screen Shot 2021-09-24 at 13 10 04](https://user-images.githubusercontent.com/43000324/134714438-faed29a7-b5a8-47b0-b1d2-257f566c5f9a.png)

**Comment by GustavoTCh** [comment]
@ValorNaram  @SamuelRioTz That's right, The plan has "Itineraries", and the "Itinerary" has "Legs", and the "Leg" has a "Route" and finally the "Route" has Color

**Comment by ZihRah** [comment]
Colour code from Sandra: https://xd.adobe.com/view/bb55b14d-0b62-4c07-ae6b-e693eadd890c-ee06/
