### ISSUE TITLE
BUG: Button without functionality

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#76]
The button ![image](https://user-images.githubusercontent.com/70654680/134392051-cc94b616-74ed-43d1-a4c9-73a0e5831190.png) doesn't have functionality

It should refresh the current page.

**Comment by SamuelRioTz** [comment]
@ZihRah what exactly means "refresh the current page" ?

**Comment by ZihRah** [comment]
Remove the icon.
