### ISSUE TITLE
BUG: Empty Space when place is unknown

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#80]
The app shows an empty space (in origin or destination) when a place is unknown.

![Bildschirmfoto 2021-09-22 um 19 36 48](https://user-images.githubusercontent.com/70654680/134393681-2985cd5d-c8b5-4969-b516-fb7ffcd7a67b.png)

https://drive.google.com/file/d/1m1dxUf7y7laLEWV6oYouiowW_l2pnkUZ/view?usp=sharing

**Comment by SamuelRioTz** [comment]
@GustavoTCh use "unknown" instead empty string, I guess is a bug

**Comment by GustavoTCh** [comment]
@ZihRah  Could you provide more information about how to reproduce this bug?

**Comment by GustavoTCh** [comment]
I managed to reproduce the bug.
