### ISSUE TITLE
BUG: Transport change not clear

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#81]
See the point of transfer(transport change) is not clear because the lines are thick.
![Bildschirmfoto 2021-09-22 um 19 45 08](https://user-images.githubusercontent.com/70654680/134394854-d8e33cdc-d1fe-4a69-b815-119777e9d41c.png)

**Comment by SamuelRioTz** [comment]
@ZihRah  how could be the fix? decrease the circle radius? change color?

**Comment by ZihRah** [comment]
Please make one point out of two. so it looks better.
