### ISSUE TITLE
BUG: Difficulty to recognize favorite places

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#83]
To add a favorite place I suggest that first, it permits us to select an icon or put a name. Currently, it is difficult to recognize what we save as a favorite place.

![Bildschirmfoto 2021-09-22 um 19 49 38](https://user-images.githubusercontent.com/70654680/134395506-e0912318-706a-4a80-979f-9ba905b403f9.png)

**Comment by SamuelRioTz** [comment]
@ZihRah could you provide a design

**Comment by ZihRah** [comment]
Add the functunality from stadtnavi to solve this problem.
