### ISSUE TITLE
BUG: Size of Key visual

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#88]
The main image is small at the start screen and the main screen

![Bildschirmfoto 2021-09-26 um 13 06 28](https://user-images.githubusercontent.com/70654680/134805140-913b2a8a-02ed-4ce9-8a02-01dea60b5a51.png)

Big screen 10.5
Resolution:
2560x1600

**Comment by AnivlisLuz** [comment]
The start screen still is small on the big screens.

**Comment by SamuelRioTz** [comment]
@AnivlisLuz please share a screenshot
