### ISSUE TITLE
Frontend: Create App Icon

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/hamburg-bike-app#92]
The App Icon for the Appstore is missing and need to be generated.

**Comment by SamuelRioTz** [comment]
@ZihRah what is the icon?

**Comment by ZihRah** [comment]
It is the icon you have on the Appstore and on your mobile phone after the download.

**Comment by SamuelRioTz** [comment]
ok, but I mean: where is the icon? or which icon should I use?

**Comment by ZihRah** [comment]
That's what the Icon should look like: https://xd.adobe.com/view/163b79a8-a022-45db-83c6-708ee82ea33e-4368/

**Comment by AnivlisLuz** [comment]
The App Icon for the App Store hasn't been changed yet. 
![image](https://user-images.githubusercontent.com/42398857/135218171-9be44922-f2a2-4900-b427-1269bcc51461.png)
